
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '35B0B80416DB3274F3383A330F6A6B9C'
    
_lr_action_items = {'LABEL':([0,10,14,],[3,13,20,]),'OPCODE':([0,],[5,]),'NEWLINE':([0,6,8,11,12,13,18,19,20,],[4,9,-9,15,16,17,21,22,23,]),'$end':([1,2,4,9,15,16,17,21,22,23,],[0,-1,-10,-2,-4,-6,-7,-3,-5,-8,]),'COLUMN':([3,],[6,]),'REGISTER':([5,10,14,],[8,8,8,]),'COMMA':([7,8,11,],[10,-9,14,]),'IMMEDIATE':([10,14,],[12,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,],[2,]),'register':([5,10,14,],[7,11,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program_statement','parser.py',33),
  ('program -> LABEL COLUMN NEWLINE','program',3,'p_program_label','parser.py',41),
  ('statement -> OPCODE register COMMA register COMMA register NEWLINE','statement',7,'p_statement_R','parser.py',53),
  ('statement -> OPCODE register COMMA register NEWLINE','statement',5,'p_statement_CR','parser.py',67),
  ('statement -> OPCODE register COMMA register COMMA IMMEDIATE NEWLINE','statement',7,'p_statement_I_S_SB','parser.py',80),
  ('statement -> OPCODE register COMMA IMMEDIATE NEWLINE','statement',5,'p_statement_U_UJ_CI','parser.py',137),
  ('statement -> OPCODE register COMMA LABEL NEWLINE','statement',5,'p_statement_UJ_LABEL','parser.py',182),
  ('statement -> OPCODE register COMMA register COMMA LABEL NEWLINE','statement',7,'p_statement_SB__JALR_LABEL','parser.py',198),
  ('register -> REGISTER','register',1,'p_register','parser.py',223),
  ('statement -> NEWLINE','statement',1,'p_statement_none','parser.py',235),
]
